// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for PatientGender.
const (
	PatientGenderFemale PatientGender = "Female"
	PatientGenderMale   PatientGender = "Male"
	PatientGenderOther  PatientGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientGender enum.
func (e PatientGender) Valid() bool {
	switch e {
	case PatientGenderFemale:
		return true
	case PatientGenderMale:
		return true
	case PatientGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PatientCreateGender.
const (
	PatientCreateGenderFemale PatientCreateGender = "Female"
	PatientCreateGenderMale   PatientCreateGender = "Male"
	PatientCreateGenderOther  PatientCreateGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientCreateGender enum.
func (e PatientCreateGender) Valid() bool {
	switch e {
	case PatientCreateGenderFemale:
		return true
	case PatientCreateGenderMale:
		return true
	case PatientCreateGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PatientUpdateGender.
const (
	Female PatientUpdateGender = "Female"
	Male   PatientUpdateGender = "Male"
	Other  PatientUpdateGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientUpdateGender enum.
func (e PatientUpdateGender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email openapi_types.Email `json:"email"`
	Id    int64               `json:"id"`
	Name  string              `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Message Human-readable error message.
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`

	// Username User's email address. Named `username` to match Laravel's login input.
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Signed JWT (HS256). Use as `Authorization: Bearer <token>`.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds remaining until the token expires.
	ExpiresIn int                    `json:"expires_in"`
	TokenType LoginResponseTokenType `json:"token_type"`
	User      AuthUser               `json:"user"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// PaginatedPatients defines model for PaginatedPatients.
type PaginatedPatients struct {
	Data []Patient      `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	CurrentPage int   `json:"current_page"`
	LastPage    int   `json:"last_page"`
	PerPage     int   `json:"per_page"`
	Total       int64 `json:"total"`
}

// Patient defines model for Patient.
type Patient struct {
	Address     *string              `json:"address,omitempty"`
	CreatedAt   time.Time            `json:"created_at"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	DeletedAt   *time.Time           `json:"deleted_at,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`

	// FullName Computed accessor — `first_name` + " " + `last_name`. Read-only.
	FullName  *string        `json:"full_name,omitempty"`
	Gender    *PatientGender `json:"gender,omitempty"`
	Id        int64          `json:"id"`
	LastName  string         `json:"last_name"`
	Phone     *string        `json:"phone,omitempty"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// PatientGender defines model for Patient.Gender.
type PatientGender string

// PatientCreate defines model for PatientCreate.
type PatientCreate struct {
	Address     *string              `json:"address,omitempty"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`
	Gender      *PatientCreateGender `json:"gender,omitempty"`
	LastName    string               `json:"last_name"`
	Phone       *string              `json:"phone,omitempty"`
}

// PatientCreateGender defines model for PatientCreate.Gender.
type PatientCreateGender string

// PatientEnvelope defines model for PatientEnvelope.
type PatientEnvelope struct {
	Data Patient `json:"data"`
}

// PatientUpdate All fields are optional. Only keys present in the request body
// are written; explicit `null` clears a nullable column.
type PatientUpdate struct {
	Address     *string              `json:"address,omitempty"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   *string              `json:"first_name,omitempty"`
	Gender      *PatientUpdateGender `json:"gender,omitempty"`
	LastName    *string              `json:"last_name,omitempty"`
	Phone       *string              `json:"phone,omitempty"`
}

// PatientUpdateGender defines model for PatientUpdate.Gender.
type PatientUpdateGender string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Errors Map of field name → list of error messages, matching Laravel's 422 shape.
	Errors  map[string][]string `json:"errors"`
	Message string              `json:"message"`
}

// Page defines model for Page.
type Page = int

// PatientId defines model for PatientId.
type PatientId = int64

// PerPage defines model for PerPage.
type PerPage = int

// Search defines model for Search.
type Search = string

// Sort defines model for Sort.
type Sort = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListPatientsParams defines parameters for ListPatients.
type ListPatientsParams struct {
	// Page 1-indexed page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size.
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Search Case-insensitive substring match across the resource's searchable columns.
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Column to sort by. Prefix with `-` for descending (e.g. `-created_at`).
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// CreatePatientJSONRequestBody defines body for CreatePatient for application/json ContentType.
type CreatePatientJSONRequestBody = PatientCreate

// UpdatePatientJSONRequestBody defines body for UpdatePatient for application/json ContentType.
type UpdatePatientJSONRequestBody = PatientUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate and receive a JWT.
	// (POST /auth/login)
	LoginUser(c *gin.Context)
	// List patients with pagination, search, and sort.
	// (GET /patients)
	ListPatients(c *gin.Context, params ListPatientsParams)
	// Create a new patient.
	// (POST /patients)
	CreatePatient(c *gin.Context)
	// Soft-delete a patient.
	// (DELETE /patients/{id})
	DeletePatient(c *gin.Context, id PatientId)
	// Fetch a single patient by id.
	// (GET /patients/{id})
	GetPatient(c *gin.Context, id PatientId)
	// Update a patient (partial merge).
	// (PUT /patients/{id})
	UpdatePatient(c *gin.Context, id PatientId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c)
}

// ListPatients operation middleware
func (siw *ServerInterfaceWrapper) ListPatients(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPatientsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPatients(c, params)
}

// CreatePatient operation middleware
func (siw *ServerInterfaceWrapper) CreatePatient(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePatient(c)
}

// DeletePatient operation middleware
func (siw *ServerInterfaceWrapper) DeletePatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePatient(c, id)
}

// GetPatient operation middleware
func (siw *ServerInterfaceWrapper) GetPatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPatient(c, id)
}

// UpdatePatient operation middleware
func (siw *ServerInterfaceWrapper) UpdatePatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePatient(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.LoginUser)
	router.GET(options.BaseURL+"/patients", wrapper.ListPatients)
	router.POST(options.BaseURL+"/patients", wrapper.CreatePatient)
	router.DELETE(options.BaseURL+"/patients/:id", wrapper.DeletePatient)
	router.GET(options.BaseURL+"/patients/:id", wrapper.GetPatient)
	router.PUT(options.BaseURL+"/patients/:id", wrapper.UpdatePatient)
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse ValidationError

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse LoginResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser422JSONResponse struct{ ValidationErrorJSONResponse }

func (response LoginUser422JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatientsRequestObject struct {
	Params ListPatientsParams
}

type ListPatientsResponseObject interface {
	VisitListPatientsResponse(w http.ResponseWriter) error
}

type ListPatients200JSONResponse PaginatedPatients

func (response ListPatients200JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatients400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPatients400JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatients401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPatients401JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatientRequestObject struct {
	Body *CreatePatientJSONRequestBody
}

type CreatePatientResponseObject interface {
	VisitCreatePatientResponse(w http.ResponseWriter) error
}

type CreatePatient201JSONResponse PatientEnvelope

func (response CreatePatient201JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePatient400JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePatient401JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreatePatient422JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePatientRequestObject struct {
	Id PatientId `json:"id"`
}

type DeletePatientResponseObject interface {
	VisitDeletePatientResponse(w http.ResponseWriter) error
}

type DeletePatient204Response struct {
}

func (response DeletePatient204Response) VisitDeletePatientResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePatient401JSONResponse) VisitDeletePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePatient404JSONResponse struct{ NotFoundJSONResponse }

func (response DeletePatient404JSONResponse) VisitDeletePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatientRequestObject struct {
	Id PatientId `json:"id"`
}

type GetPatientResponseObject interface {
	VisitGetPatientResponse(w http.ResponseWriter) error
}

type GetPatient200JSONResponse PatientEnvelope

func (response GetPatient200JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPatient401JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatient404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPatient404JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatientRequestObject struct {
	Id   PatientId `json:"id"`
	Body *UpdatePatientJSONRequestBody
}

type UpdatePatientResponseObject interface {
	VisitUpdatePatientResponse(w http.ResponseWriter) error
}

type UpdatePatient200JSONResponse PatientEnvelope

func (response UpdatePatient200JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdatePatient401JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdatePatient404JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdatePatient422JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate and receive a JWT.
	// (POST /auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// List patients with pagination, search, and sort.
	// (GET /patients)
	ListPatients(ctx context.Context, request ListPatientsRequestObject) (ListPatientsResponseObject, error)
	// Create a new patient.
	// (POST /patients)
	CreatePatient(ctx context.Context, request CreatePatientRequestObject) (CreatePatientResponseObject, error)
	// Soft-delete a patient.
	// (DELETE /patients/{id})
	DeletePatient(ctx context.Context, request DeletePatientRequestObject) (DeletePatientResponseObject, error)
	// Fetch a single patient by id.
	// (GET /patients/{id})
	GetPatient(ctx context.Context, request GetPatientRequestObject) (GetPatientResponseObject, error)
	// Update a patient (partial merge).
	// (PUT /patients/{id})
	UpdatePatient(ctx context.Context, request UpdatePatientRequestObject) (UpdatePatientResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx *gin.Context) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPatients operation middleware
func (sh *strictHandler) ListPatients(ctx *gin.Context, params ListPatientsParams) {
	var request ListPatientsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPatients(ctx, request.(ListPatientsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPatients")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListPatientsResponseObject); ok {
		if err := validResponse.VisitListPatientsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePatient operation middleware
func (sh *strictHandler) CreatePatient(ctx *gin.Context) {
	var request CreatePatientRequestObject

	var body CreatePatientJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePatient(ctx, request.(CreatePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreatePatientResponseObject); ok {
		if err := validResponse.VisitCreatePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePatient operation middleware
func (sh *strictHandler) DeletePatient(ctx *gin.Context, id PatientId) {
	var request DeletePatientRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePatient(ctx, request.(DeletePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeletePatientResponseObject); ok {
		if err := validResponse.VisitDeletePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPatient operation middleware
func (sh *strictHandler) GetPatient(ctx *gin.Context, id PatientId) {
	var request GetPatientRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPatient(ctx, request.(GetPatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPatientResponseObject); ok {
		if err := validResponse.VisitGetPatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePatient operation middleware
func (sh *strictHandler) UpdatePatient(ctx *gin.Context, id PatientId) {
	var request UpdatePatientRequestObject

	request.Id = id

	var body UpdatePatientJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePatient(ctx, request.(UpdatePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdatePatientResponseObject); ok {
		if err := validResponse.VisitUpdatePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFpvb9s40v8qA+0DNMnKspttFwsvHuBpu223fdJt0LjXF3EQ0eLY4kYitSTlxBsEuFf3AQ73CfeTHIaU",
	"bMmW4+Sa5oACTSRyZjh/fpz5KddBovJCSZTWBMProGCa5WhRu9+O2Qzpf44m0aKwQslgGDztCcnxCjkU",
	"bIYgy3yCOgrCQNDbP0rUiyAMJMsxGAa0JAgDk6SYMy9rysrMBsOnYZALKfIydz/bRUHrhbQ4Qx3c3ITB",
	"MbMCpX3HN22oXsG7X5aKC2bTlV7BgzDQ+EcpNPJgaHWJTSumSufMen0/Pgt2m4K62xn0FIz4E7c6APX5",
	"diccPg+DnF1VqgeDnYacINNJumnHK2awJ6RBaYQVcwRTTozVQs4gZzZJgSVaGQM2RdBoVKkTfGLAOHFs",
	"kiEkKitzabadw69snaIyz6vx1iltO2xzksEqMEpbmCwiONY4FVdwKWwKcS+GqdJAm1ByMnkPo1kEcS/R",
	"yCzyc2bj/a2Gkc7bzLqhRDCFkgZdVr9k/BP+UaJxpiZKWpTuR1YUmUgYWd3/3ZDp1w2x/6NxGgyD7/qr",
	"iun7t6b/Wmulvar20T+wjFINOTirYVVfoDRobwZMFF9EwU0Y/KbsG1VK/u0N+1TlAEhlYUo6nQGfJStt",
	"qrT4Ex/BiA/CGAq30iDknGWCwwSZRg1WXaB0Fv2NHjutXsxDGbUut9NHq/DAlIkMOcyX2yKX8ZU40vai",
	"tOlng87EQqsCtRU+4zBnImvBjn8SrudqSLjVBU/rSFBnf1cRrlDv1MOgWxpWOs+WwtTkd0wsyVp6tm12",
	"jsZ0gt6vZc5kTyPjDjmQtkO1Oto81ZpNtdguS47UTMhGdbYNKpgxl0q3XbR86LDzCOXMpk30XPm2NKhr",
	"t7UPRGF7YsB5CBjnGo2J4DdGhRvX22JCMA+mR0yzOWZPDGRkMAhZlJZOjlcsLzJSy1Vilf6/6kGUqHyn",
	"Y5b2hatD3eIkD2mbXmJJgsacuxLaPOqJmEnk8P7LCPZ+PTl8/uN+BJ8NAjMQv6hq3+X3EF76WhyXg8EP",
	"iRPnfsQ46spcvCqERnMuupRioiQ3oMnDkkq+lFZk7jZygqHaHXXmulty7p9fByjpejwNvHkND7UjvQsA",
	"luW6HoaW/1rKW4estHQF6JjNhKSLq2pTzGaQOLMOooTF3OwytRLjXOF1Ma3Zgn7P0bLd2505QskPtHr9",
	"vM6UStItp6m3bxwlKbVGaX2XQ7BxSwcTBhkzd126bJ12rrTKsuz2vm7Q2U41/dA6R9hs3Lz4pu3dfvJR",
	"2ixIDyjuGOyqRqjD58/DQJZZRhhad6gbmbzqgFrH48xizwqHFRt76OW5mp5PhLbpxrbgDlo5ZrhD604Z",
	"2y+9hhNcy7tT1FRoY89r6F7fvrm8zLLzbqB/pfKitMjBF7nS8Nff/wXxSkEM38M4oH/fQ+zi7Z5G8AkZ",
	"7ymZLSI3WDD+UWaLrRbPUHIPQTVafWAZue0N5v6Hjzb16LHz9HduCZbm3slLRark+srDu0SjLPg9U7Kr",
	"KWnEtGl5M3qt7G/pvaX8Xrkt9yrC+xfQVyT7PZN7R0tzjzzb2HtruuzQuy15bg/8lpjfEs3Xco6ZKnD7",
	"BXqne7PrxrtF62eXaZvo8SLLYCow4waYRlDuOcsiICyAC1wYKDQalBaErEbt1QgxlrTpUgtrUf5MHU8m",
	"EmEhpoqLIcmQaQMM6gKsJvJoTL3Gw90oX387PBqyP1zy7zTkWxTDDqU3HQnYMe2ujZL0uM4B4fPvuLVi",
	"2VFu2LneO65TFQWoqc9vIE/AX//4J2TCWHrcmvFM6OcgauRXo9Czw0MwKSuaI+DqZI1hcjUkjVKEmZij",
	"BCpJuGSmJgLuPkaGtU82C5rmc0xKLezihCDBO8hTDNT+r357U2fy+y+jYN0zNCsJY0rkMFlAfPzxZAR9",
	"Vtq076a/GPY4TgVNVUICg4xZ1GDKSc9YLPajsRzVY84TA0bM3AB0gQtgksNodASJyhGmWuUQv/8yOj95",
	"/erT61EMff/raHQUj2UFKCZlmobSCOU8hqnI0OODgzw6uz/PynuptYUnN4Scqk1Me6tg762Q8D28/fjp",
	"wz5MWHKBkoPGImMJWUpqqyj3X7LkomDJBTCeC+loO5viWCaZkCIh+FPk+ghGqTDAVVLmDg098WiEnGUI",
	"FfOkpmB1adOVlF9Ho2NIlLSaJfZniBUrRC9RHGcoY3phyhwNCEuTeKEVLxP0glHPUZOTLOopSxAEZRjp",
	"9lGJ3RvJsj4rRD+OxnIsv/sOXik5R0meMGPZg4OD1awTHRy4uTimfj+GvSXrve/CFtfjgWsNK3ZxLAFY",
	"dskWlMZJVnIEBjENVjH4nBxC3Bwz4rAhKITYDRpxSHLi5bBB1pJtnvolu17Unow9Kxuvs4tQoCZwNsBI",
	"VnJHchhZkjbZ4Tp+yEnKJlcMewZ9AFDyQglpoZFc+7XdSluyOjZK2//1Wz3jy2rCN6xe9ppvV3xwJchf",
	"y2AwZ9KKxDihx59HsevmC0uX58FBwbQVLDs48Lwd9ffUtvsMg/YtTRdy1VZWKSsctehgNVtALhy0+CNe",
	"CWOFnJGQtTKYYMrmQpUaNKMbB2zKJJCHEwufXp+Mqmpq2u6P5FDeHYTQc0lTw1RlmbpsgKsDVlK9F1/X",
	"MBx6VDZDuPawPYTT3MxCiKLoDG7gJt4HozaMn2rHn/InpsFm9rgwRcYWQOUGF4iFgUulL7z3CU6EdZD9",
	"qqr0F8fvgjCYozYeRwbR02hAQK8KlKwQwTD4IRpEPzgyy6YOeRug6W42ZTq+FnyofL46u+OlhsNZyTTf",
	"e8IK8WS/55koZi3mhd07ramzEGrm7Gw/Hstppi6HzgENFs/fcBUklR3MH+xJx/wZRXk4lpdCU8rnBbNi",
	"IjJhF/7DRdOxTa96TpDqb9/7jq5n5+V3PBh6+s4xT/5CQ2NfKr54MGa7xaHetK9NakTWv4ccDgYPrbui",
	"Jjs4dQolFVjiao7y5dng6TapSzP7re8StOnwcPemTYp/1Q8Ew9OzMDBlnjO9WLPLAbzGBAkqGbz/MnLd",
	"CJsZ6jtc43BGsvpFg96bYUcuL/HZwSwaYDMmpLEtxiFsEg0hxC4X45CsGMvYNZcx7G1g+NG7/3+97y4y",
	"AtgmLA8hFpwk3aKkNQXQjbNUGzc+uoUQr6buuDOZhbFLljNsfT8+7Y7PaknffVK9CXevq76+3mFp9X30",
	"LiuVtsHN2Tcshk0auKMglougyibXcleVMdid5I2vmf9ZMd00y4DCWRtiPMoVy5YorFoAl5ruW26zLpaH",
	"PKORqIL2drJ4bqaeyr8N+rVpoDvB39OHVr5kLTrj7aNcVdkjBvprUHOZIN6vwEDiZZ0oW7KgiZD9a8Fv",
	"PD5m2EWtnKA1EK945/hnz5+oS7qpXb+m58hd5uGV6625H5mqv6UYS+qBBRqYC+ZmGeqa1NT2vFBImeTZ",
	"sp1pJ+YvbkkzMVsJ8mzTXr/ja24wL/X2Tcu/B2gH4aRxLLYjCmF9M7VP/Bbt1uMOHrMe1MV/xYVv0M09",
	"9SBVY+9kARX30Ilq97zd6j9folumKDv6A8cbVoziLcxhe075mAsLzBEIVo1lhmyOIKzr5kuEUiYpkzNa",
	"+bqbYiTxvgneu0xR41jSE988ULXVvFVn9+qHsEfB8IqGfeQW9h4YXofksTL4QRC8mqKXuAF71cQMOeoZ",
	"7m9D83bz3KbRTs8oxT0L42uj7bAjlbAMODqX5hVYlTqr+Klhv5/RilQZO/xp8NPAVUxlxPX2CUIo6VsR",
	"NDSFOpKOycQRkNVfhzn7qBvsjiDHXM00K1KRUMevNDeNzau+7ezm3wEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
