// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AppointmentStatus.
const (
	AppointmentStatusCancelled AppointmentStatus = "Cancelled"
	AppointmentStatusCompleted AppointmentStatus = "Completed"
	AppointmentStatusConfirmed AppointmentStatus = "Confirmed"
	AppointmentStatusScheduled AppointmentStatus = "Scheduled"
)

// Valid indicates whether the value is a known member of the AppointmentStatus enum.
func (e AppointmentStatus) Valid() bool {
	switch e {
	case AppointmentStatusCancelled:
		return true
	case AppointmentStatusCompleted:
		return true
	case AppointmentStatusConfirmed:
		return true
	case AppointmentStatusScheduled:
		return true
	default:
		return false
	}
}

// Defines values for AppointmentCreateStatus.
const (
	AppointmentCreateStatusCancelled AppointmentCreateStatus = "Cancelled"
	AppointmentCreateStatusCompleted AppointmentCreateStatus = "Completed"
	AppointmentCreateStatusConfirmed AppointmentCreateStatus = "Confirmed"
	AppointmentCreateStatusScheduled AppointmentCreateStatus = "Scheduled"
)

// Valid indicates whether the value is a known member of the AppointmentCreateStatus enum.
func (e AppointmentCreateStatus) Valid() bool {
	switch e {
	case AppointmentCreateStatusCancelled:
		return true
	case AppointmentCreateStatusCompleted:
		return true
	case AppointmentCreateStatusConfirmed:
		return true
	case AppointmentCreateStatusScheduled:
		return true
	default:
		return false
	}
}

// Defines values for AppointmentUpdateStatus.
const (
	AppointmentUpdateStatusCancelled AppointmentUpdateStatus = "Cancelled"
	AppointmentUpdateStatusCompleted AppointmentUpdateStatus = "Completed"
	AppointmentUpdateStatusConfirmed AppointmentUpdateStatus = "Confirmed"
	AppointmentUpdateStatusScheduled AppointmentUpdateStatus = "Scheduled"
)

// Valid indicates whether the value is a known member of the AppointmentUpdateStatus enum.
func (e AppointmentUpdateStatus) Valid() bool {
	switch e {
	case AppointmentUpdateStatusCancelled:
		return true
	case AppointmentUpdateStatusCompleted:
		return true
	case AppointmentUpdateStatusConfirmed:
		return true
	case AppointmentUpdateStatusScheduled:
		return true
	default:
		return false
	}
}

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for PatientGender.
const (
	PatientGenderFemale PatientGender = "Female"
	PatientGenderMale   PatientGender = "Male"
	PatientGenderOther  PatientGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientGender enum.
func (e PatientGender) Valid() bool {
	switch e {
	case PatientGenderFemale:
		return true
	case PatientGenderMale:
		return true
	case PatientGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PatientCreateGender.
const (
	PatientCreateGenderFemale PatientCreateGender = "Female"
	PatientCreateGenderMale   PatientCreateGender = "Male"
	PatientCreateGenderOther  PatientCreateGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientCreateGender enum.
func (e PatientCreateGender) Valid() bool {
	switch e {
	case PatientCreateGenderFemale:
		return true
	case PatientCreateGenderMale:
		return true
	case PatientCreateGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PatientUpdateGender.
const (
	Female PatientUpdateGender = "Female"
	Male   PatientUpdateGender = "Male"
	Other  PatientUpdateGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientUpdateGender enum.
func (e PatientUpdateGender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for ListAppointmentsParamsStatus.
const (
	ListAppointmentsParamsStatusCancelled ListAppointmentsParamsStatus = "Cancelled"
	ListAppointmentsParamsStatusCompleted ListAppointmentsParamsStatus = "Completed"
	ListAppointmentsParamsStatusConfirmed ListAppointmentsParamsStatus = "Confirmed"
	ListAppointmentsParamsStatusScheduled ListAppointmentsParamsStatus = "Scheduled"
)

// Valid indicates whether the value is a known member of the ListAppointmentsParamsStatus enum.
func (e ListAppointmentsParamsStatus) Valid() bool {
	switch e {
	case ListAppointmentsParamsStatusCancelled:
		return true
	case ListAppointmentsParamsStatusCompleted:
		return true
	case ListAppointmentsParamsStatusConfirmed:
		return true
	case ListAppointmentsParamsStatusScheduled:
		return true
	default:
		return false
	}
}

// Appointment defines model for Appointment.
type Appointment struct {
	AppointmentDateTime time.Time  `json:"appointment_date_time"`
	CreatedAt           time.Time  `json:"created_at"`
	DeletedAt           *time.Time `json:"deleted_at,omitempty"`
	DurationMinutes     int        `json:"duration_minutes"`
	Id                  int64      `json:"id"`

	// Patient Minimal patient embed used inside appointment responses.
	Patient        *AppointmentPatient `json:"patient,omitempty"`
	PatientId      int64               `json:"patient_id"`
	ReasonForVisit *string             `json:"reason_for_visit,omitempty"`
	Status         AppointmentStatus   `json:"status"`
	UpdatedAt      time.Time           `json:"updated_at"`

	// User Minimal user embed used inside appointment responses.
	User   *AppointmentUser `json:"user,omitempty"`
	UserId int64            `json:"user_id"`
}

// AppointmentStatus defines model for Appointment.Status.
type AppointmentStatus string

// AppointmentCreate defines model for AppointmentCreate.
type AppointmentCreate struct {
	AppointmentDateTime time.Time                `json:"appointment_date_time"`
	DurationMinutes     *int                     `json:"duration_minutes,omitempty"`
	PatientId           int64                    `json:"patient_id"`
	ReasonForVisit      *string                  `json:"reason_for_visit,omitempty"`
	Status              *AppointmentCreateStatus `json:"status,omitempty"`
	UserId              int64                    `json:"user_id"`
}

// AppointmentCreateStatus defines model for AppointmentCreate.Status.
type AppointmentCreateStatus string

// AppointmentEnvelope defines model for AppointmentEnvelope.
type AppointmentEnvelope struct {
	Data Appointment `json:"data"`
}

// AppointmentPatient Minimal patient embed used inside appointment responses.
type AppointmentPatient struct {
	FullName string `json:"full_name"`
	Id       int64  `json:"id"`
}

// AppointmentUpdate Partial merge — only present fields are written. Same nullable
// caveat as PatientUpdate.
type AppointmentUpdate struct {
	AppointmentDateTime *time.Time               `json:"appointment_date_time,omitempty"`
	DurationMinutes     *int                     `json:"duration_minutes,omitempty"`
	PatientId           *int64                   `json:"patient_id,omitempty"`
	ReasonForVisit      *string                  `json:"reason_for_visit,omitempty"`
	Status              *AppointmentUpdateStatus `json:"status,omitempty"`
	UserId              *int64                   `json:"user_id,omitempty"`
}

// AppointmentUpdateStatus defines model for AppointmentUpdate.Status.
type AppointmentUpdateStatus string

// AppointmentUser Minimal user embed used inside appointment responses.
type AppointmentUser struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Id    int64                `json:"id"`
	Name  string               `json:"name"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email openapi_types.Email `json:"email"`
	Id    int64               `json:"id"`
	Name  string              `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Message Human-readable error message.
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`

	// Username User's email address. Named `username` to match Laravel's login input.
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Signed JWT (HS256). Use as `Authorization: Bearer <token>`.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds remaining until the token expires.
	ExpiresIn int                    `json:"expires_in"`
	TokenType LoginResponseTokenType `json:"token_type"`
	User      AuthUser               `json:"user"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// PaginatedAppointments defines model for PaginatedAppointments.
type PaginatedAppointments struct {
	Data []Appointment  `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// PaginatedPatients defines model for PaginatedPatients.
type PaginatedPatients struct {
	Data []Patient      `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	CurrentPage int   `json:"current_page"`
	LastPage    int   `json:"last_page"`
	PerPage     int   `json:"per_page"`
	Total       int64 `json:"total"`
}

// Patient defines model for Patient.
type Patient struct {
	Address     *string              `json:"address,omitempty"`
	CreatedAt   time.Time            `json:"created_at"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	DeletedAt   *time.Time           `json:"deleted_at,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`

	// FullName Computed accessor — `first_name` + " " + `last_name`. Read-only.
	FullName  *string        `json:"full_name,omitempty"`
	Gender    *PatientGender `json:"gender,omitempty"`
	Id        int64          `json:"id"`
	LastName  string         `json:"last_name"`
	Phone     *string        `json:"phone,omitempty"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// PatientGender defines model for Patient.Gender.
type PatientGender string

// PatientCreate defines model for PatientCreate.
type PatientCreate struct {
	Address     *string              `json:"address,omitempty"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`
	Gender      *PatientCreateGender `json:"gender,omitempty"`
	LastName    string               `json:"last_name"`
	Phone       *string              `json:"phone,omitempty"`
}

// PatientCreateGender defines model for PatientCreate.Gender.
type PatientCreateGender string

// PatientEnvelope defines model for PatientEnvelope.
type PatientEnvelope struct {
	Data Patient `json:"data"`
}

// PatientUpdate All fields are optional. Only keys present in the request body
// are written; explicit `null` clears a nullable column.
type PatientUpdate struct {
	Address     *string              `json:"address,omitempty"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   *string              `json:"first_name,omitempty"`
	Gender      *PatientUpdateGender `json:"gender,omitempty"`
	LastName    *string              `json:"last_name,omitempty"`
	Phone       *string              `json:"phone,omitempty"`
}

// PatientUpdateGender defines model for PatientUpdate.Gender.
type PatientUpdateGender string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Errors Map of field name → list of error messages, matching Laravel's 422 shape.
	Errors  map[string][]string `json:"errors"`
	Message string              `json:"message"`
}

// AppointmentId defines model for AppointmentId.
type AppointmentId = int64

// Page defines model for Page.
type Page = int

// PatientId defines model for PatientId.
type PatientId = int64

// PerPage defines model for PerPage.
type PerPage = int

// Search defines model for Search.
type Search = string

// Sort defines model for Sort.
type Sort = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAppointmentsParams defines parameters for ListAppointments.
type ListAppointmentsParams struct {
	// Page 1-indexed page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size.
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Search Case-insensitive substring match across the resource's searchable columns.
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Column to sort by. Prefix with `-` for descending (e.g. `-created_at`).
	Sort      *Sort                         `form:"sort,omitempty" json:"sort,omitempty"`
	Status    *ListAppointmentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	PatientId *int64                        `form:"patient_id,omitempty" json:"patient_id,omitempty"`
	UserId    *int64                        `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// ListAppointmentsParamsStatus defines parameters for ListAppointments.
type ListAppointmentsParamsStatus string

// ListPatientsParams defines parameters for ListPatients.
type ListPatientsParams struct {
	// Page 1-indexed page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size.
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Search Case-insensitive substring match across the resource's searchable columns.
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Column to sort by. Prefix with `-` for descending (e.g. `-created_at`).
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`
}

// CreateAppointmentJSONRequestBody defines body for CreateAppointment for application/json ContentType.
type CreateAppointmentJSONRequestBody = AppointmentCreate

// UpdateAppointmentJSONRequestBody defines body for UpdateAppointment for application/json ContentType.
type UpdateAppointmentJSONRequestBody = AppointmentUpdate

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// CreatePatientJSONRequestBody defines body for CreatePatient for application/json ContentType.
type CreatePatientJSONRequestBody = PatientCreate

// UpdatePatientJSONRequestBody defines body for UpdatePatient for application/json ContentType.
type UpdatePatientJSONRequestBody = PatientUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List appointments with pagination, search, sort, and filters.
	// (GET /appointments)
	ListAppointments(c *gin.Context, params ListAppointmentsParams)
	// Create a new appointment.
	// (POST /appointments)
	CreateAppointment(c *gin.Context)
	// Soft-delete an appointment.
	// (DELETE /appointments/{id})
	DeleteAppointment(c *gin.Context, id AppointmentId)
	// Fetch a single appointment by id.
	// (GET /appointments/{id})
	GetAppointment(c *gin.Context, id AppointmentId)
	// Update an appointment (partial merge).
	// (PUT /appointments/{id})
	UpdateAppointment(c *gin.Context, id AppointmentId)
	// Authenticate and receive a JWT.
	// (POST /auth/login)
	LoginUser(c *gin.Context)
	// List patients with pagination, search, and sort.
	// (GET /patients)
	ListPatients(c *gin.Context, params ListPatientsParams)
	// Create a new patient.
	// (POST /patients)
	CreatePatient(c *gin.Context)
	// Soft-delete a patient.
	// (DELETE /patients/{id})
	DeletePatient(c *gin.Context, id PatientId)
	// Fetch a single patient by id.
	// (GET /patients/{id})
	GetPatient(c *gin.Context, id PatientId)
	// Update a patient (partial merge).
	// (PUT /patients/{id})
	UpdatePatient(c *gin.Context, id PatientId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAppointments operation middleware
func (siw *ServerInterfaceWrapper) ListAppointments(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAppointmentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "patient_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "patient_id", c.Request.URL.Query(), &params.PatientId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter patient_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAppointments(c, params)
}

// CreateAppointment operation middleware
func (siw *ServerInterfaceWrapper) CreateAppointment(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAppointment(c)
}

// DeleteAppointment operation middleware
func (siw *ServerInterfaceWrapper) DeleteAppointment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppointmentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAppointment(c, id)
}

// GetAppointment operation middleware
func (siw *ServerInterfaceWrapper) GetAppointment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppointmentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAppointment(c, id)
}

// UpdateAppointment operation middleware
func (siw *ServerInterfaceWrapper) UpdateAppointment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AppointmentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAppointment(c, id)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c)
}

// ListPatients operation middleware
func (siw *ServerInterfaceWrapper) ListPatients(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPatientsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPatients(c, params)
}

// CreatePatient operation middleware
func (siw *ServerInterfaceWrapper) CreatePatient(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePatient(c)
}

// DeletePatient operation middleware
func (siw *ServerInterfaceWrapper) DeletePatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePatient(c, id)
}

// GetPatient operation middleware
func (siw *ServerInterfaceWrapper) GetPatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPatient(c, id)
}

// UpdatePatient operation middleware
func (siw *ServerInterfaceWrapper) UpdatePatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePatient(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/appointments", wrapper.ListAppointments)
	router.POST(options.BaseURL+"/appointments", wrapper.CreateAppointment)
	router.DELETE(options.BaseURL+"/appointments/:id", wrapper.DeleteAppointment)
	router.GET(options.BaseURL+"/appointments/:id", wrapper.GetAppointment)
	router.PUT(options.BaseURL+"/appointments/:id", wrapper.UpdateAppointment)
	router.POST(options.BaseURL+"/auth/login", wrapper.LoginUser)
	router.GET(options.BaseURL+"/patients", wrapper.ListPatients)
	router.POST(options.BaseURL+"/patients", wrapper.CreatePatient)
	router.DELETE(options.BaseURL+"/patients/:id", wrapper.DeletePatient)
	router.GET(options.BaseURL+"/patients/:id", wrapper.GetPatient)
	router.PUT(options.BaseURL+"/patients/:id", wrapper.UpdatePatient)
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse ValidationError

type ListAppointmentsRequestObject struct {
	Params ListAppointmentsParams
}

type ListAppointmentsResponseObject interface {
	VisitListAppointmentsResponse(w http.ResponseWriter) error
}

type ListAppointments200JSONResponse PaginatedAppointments

func (response ListAppointments200JSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAppointments400JSONResponse struct{ BadRequestJSONResponse }

func (response ListAppointments400JSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAppointments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAppointments401JSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAppointmentRequestObject struct {
	Body *CreateAppointmentJSONRequestBody
}

type CreateAppointmentResponseObject interface {
	VisitCreateAppointmentResponse(w http.ResponseWriter) error
}

type CreateAppointment201JSONResponse AppointmentEnvelope

func (response CreateAppointment201JSONResponse) VisitCreateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAppointment400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAppointment400JSONResponse) VisitCreateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAppointment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAppointment401JSONResponse) VisitCreateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAppointment422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreateAppointment422JSONResponse) VisitCreateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAppointmentRequestObject struct {
	Id AppointmentId `json:"id"`
}

type DeleteAppointmentResponseObject interface {
	VisitDeleteAppointmentResponse(w http.ResponseWriter) error
}

type DeleteAppointment204Response struct {
}

func (response DeleteAppointment204Response) VisitDeleteAppointmentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAppointment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteAppointment401JSONResponse) VisitDeleteAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAppointment404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteAppointment404JSONResponse) VisitDeleteAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAppointmentRequestObject struct {
	Id AppointmentId `json:"id"`
}

type GetAppointmentResponseObject interface {
	VisitGetAppointmentResponse(w http.ResponseWriter) error
}

type GetAppointment200JSONResponse AppointmentEnvelope

func (response GetAppointment200JSONResponse) VisitGetAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAppointment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAppointment401JSONResponse) VisitGetAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAppointment404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAppointment404JSONResponse) VisitGetAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAppointmentRequestObject struct {
	Id   AppointmentId `json:"id"`
	Body *UpdateAppointmentJSONRequestBody
}

type UpdateAppointmentResponseObject interface {
	VisitUpdateAppointmentResponse(w http.ResponseWriter) error
}

type UpdateAppointment200JSONResponse AppointmentEnvelope

func (response UpdateAppointment200JSONResponse) VisitUpdateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAppointment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAppointment401JSONResponse) VisitUpdateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAppointment404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAppointment404JSONResponse) VisitUpdateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAppointment422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdateAppointment422JSONResponse) VisitUpdateAppointmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse LoginResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser422JSONResponse struct{ ValidationErrorJSONResponse }

func (response LoginUser422JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatientsRequestObject struct {
	Params ListPatientsParams
}

type ListPatientsResponseObject interface {
	VisitListPatientsResponse(w http.ResponseWriter) error
}

type ListPatients200JSONResponse PaginatedPatients

func (response ListPatients200JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatients400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPatients400JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatients401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPatients401JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatientRequestObject struct {
	Body *CreatePatientJSONRequestBody
}

type CreatePatientResponseObject interface {
	VisitCreatePatientResponse(w http.ResponseWriter) error
}

type CreatePatient201JSONResponse PatientEnvelope

func (response CreatePatient201JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePatient400JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePatient401JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreatePatient422JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePatientRequestObject struct {
	Id PatientId `json:"id"`
}

type DeletePatientResponseObject interface {
	VisitDeletePatientResponse(w http.ResponseWriter) error
}

type DeletePatient204Response struct {
}

func (response DeletePatient204Response) VisitDeletePatientResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePatient401JSONResponse) VisitDeletePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePatient404JSONResponse struct{ NotFoundJSONResponse }

func (response DeletePatient404JSONResponse) VisitDeletePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatientRequestObject struct {
	Id PatientId `json:"id"`
}

type GetPatientResponseObject interface {
	VisitGetPatientResponse(w http.ResponseWriter) error
}

type GetPatient200JSONResponse PatientEnvelope

func (response GetPatient200JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPatient401JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatient404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPatient404JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatientRequestObject struct {
	Id   PatientId `json:"id"`
	Body *UpdatePatientJSONRequestBody
}

type UpdatePatientResponseObject interface {
	VisitUpdatePatientResponse(w http.ResponseWriter) error
}

type UpdatePatient200JSONResponse PatientEnvelope

func (response UpdatePatient200JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdatePatient401JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdatePatient404JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdatePatient422JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List appointments with pagination, search, sort, and filters.
	// (GET /appointments)
	ListAppointments(ctx context.Context, request ListAppointmentsRequestObject) (ListAppointmentsResponseObject, error)
	// Create a new appointment.
	// (POST /appointments)
	CreateAppointment(ctx context.Context, request CreateAppointmentRequestObject) (CreateAppointmentResponseObject, error)
	// Soft-delete an appointment.
	// (DELETE /appointments/{id})
	DeleteAppointment(ctx context.Context, request DeleteAppointmentRequestObject) (DeleteAppointmentResponseObject, error)
	// Fetch a single appointment by id.
	// (GET /appointments/{id})
	GetAppointment(ctx context.Context, request GetAppointmentRequestObject) (GetAppointmentResponseObject, error)
	// Update an appointment (partial merge).
	// (PUT /appointments/{id})
	UpdateAppointment(ctx context.Context, request UpdateAppointmentRequestObject) (UpdateAppointmentResponseObject, error)
	// Authenticate and receive a JWT.
	// (POST /auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// List patients with pagination, search, and sort.
	// (GET /patients)
	ListPatients(ctx context.Context, request ListPatientsRequestObject) (ListPatientsResponseObject, error)
	// Create a new patient.
	// (POST /patients)
	CreatePatient(ctx context.Context, request CreatePatientRequestObject) (CreatePatientResponseObject, error)
	// Soft-delete a patient.
	// (DELETE /patients/{id})
	DeletePatient(ctx context.Context, request DeletePatientRequestObject) (DeletePatientResponseObject, error)
	// Fetch a single patient by id.
	// (GET /patients/{id})
	GetPatient(ctx context.Context, request GetPatientRequestObject) (GetPatientResponseObject, error)
	// Update a patient (partial merge).
	// (PUT /patients/{id})
	UpdatePatient(ctx context.Context, request UpdatePatientRequestObject) (UpdatePatientResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListAppointments operation middleware
func (sh *strictHandler) ListAppointments(ctx *gin.Context, params ListAppointmentsParams) {
	var request ListAppointmentsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAppointments(ctx, request.(ListAppointmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAppointments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListAppointmentsResponseObject); ok {
		if err := validResponse.VisitListAppointmentsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAppointment operation middleware
func (sh *strictHandler) CreateAppointment(ctx *gin.Context) {
	var request CreateAppointmentRequestObject

	var body CreateAppointmentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAppointment(ctx, request.(CreateAppointmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAppointment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateAppointmentResponseObject); ok {
		if err := validResponse.VisitCreateAppointmentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAppointment operation middleware
func (sh *strictHandler) DeleteAppointment(ctx *gin.Context, id AppointmentId) {
	var request DeleteAppointmentRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAppointment(ctx, request.(DeleteAppointmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAppointment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteAppointmentResponseObject); ok {
		if err := validResponse.VisitDeleteAppointmentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAppointment operation middleware
func (sh *strictHandler) GetAppointment(ctx *gin.Context, id AppointmentId) {
	var request GetAppointmentRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAppointment(ctx, request.(GetAppointmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAppointment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAppointmentResponseObject); ok {
		if err := validResponse.VisitGetAppointmentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAppointment operation middleware
func (sh *strictHandler) UpdateAppointment(ctx *gin.Context, id AppointmentId) {
	var request UpdateAppointmentRequestObject

	request.Id = id

	var body UpdateAppointmentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAppointment(ctx, request.(UpdateAppointmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAppointment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateAppointmentResponseObject); ok {
		if err := validResponse.VisitUpdateAppointmentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx *gin.Context) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPatients operation middleware
func (sh *strictHandler) ListPatients(ctx *gin.Context, params ListPatientsParams) {
	var request ListPatientsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPatients(ctx, request.(ListPatientsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPatients")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListPatientsResponseObject); ok {
		if err := validResponse.VisitListPatientsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePatient operation middleware
func (sh *strictHandler) CreatePatient(ctx *gin.Context) {
	var request CreatePatientRequestObject

	var body CreatePatientJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePatient(ctx, request.(CreatePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreatePatientResponseObject); ok {
		if err := validResponse.VisitCreatePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePatient operation middleware
func (sh *strictHandler) DeletePatient(ctx *gin.Context, id PatientId) {
	var request DeletePatientRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePatient(ctx, request.(DeletePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeletePatientResponseObject); ok {
		if err := validResponse.VisitDeletePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPatient operation middleware
func (sh *strictHandler) GetPatient(ctx *gin.Context, id PatientId) {
	var request GetPatientRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPatient(ctx, request.(GetPatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPatientResponseObject); ok {
		if err := validResponse.VisitGetPatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePatient operation middleware
func (sh *strictHandler) UpdatePatient(ctx *gin.Context, id PatientId) {
	var request UpdatePatientRequestObject

	request.Id = id

	var body UpdatePatientJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePatient(ctx, request.(UpdatePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdatePatientResponseObject); ok {
		if err := validResponse.VisitUpdatePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FttbxPJk/8qpdmT8rAT2wRYrbw66YAFFi4sETHHCxxl2jNlT29muofuHgcvinSv7gOc7hPuJzlV9zza",
	"44eEEHb/Ei+cnn6oqq6qrl9V8cULZZpJgcJob/jFy5hiKRpU9q8nWSa5MCkK8yqigQh1qHhmuBTesPkZ",
	"Xv3a83yP03DGTOz5nmApekOPR57vKfyUc4WRNzQqR9/TYYwpox2nUqXM0Dxhfnrk+V7KBU/z1Bs+8D2z",
	"yNB9whkq7/ra907ZDFcpeXDERYSfMYKMzRBEnk5QVQR9ylEtaopoitekIcIpyxNjj9x6vOFrpFF8uj9J",
	"oOoWBo2C5n/iWgGgulgvhOPHvpeyz8XRg8FWQs6QqTBepeMZ03jEhUahueFzBJ1PtFFczCBlJoyBhUpq",
	"DSZGUKhlrkLc06DtdmySIIQyyVOh1/HhZra4KMhzxzjqpDIdtNmdwUjQUhmYLHpwqnDKP8MVNzEERwFM",
	"pQJahCIikvexN+tBcBQqZAajC2aCg7WE0ZmbyLomRdCZFBqtoT1l0Tv8lKO2pIZSGBT2J8uyhIeMqO7/",
	"oYn0L41t/03h1Bt6P/RrI+67r7r/XCmp3FFt1t+whFQNI7BUQ23yIBUoRwZMZLToede+97s0L2Quom9P",
	"2LtCB0BIA1M60xLwXrDcxFLxP/EeiHjDtabrlgq4mLOERzBBplCBkZcoLEX/RcP2VLfNXRG1vG+njOrr",
	"gSnjCUYwr5b1rMYX2y05cOvdlcxQGe6UjtUfLyJm8MLwFFueiEaP7Ki/rMK+VxvC7msiTHDLGpEnCRl/",
	"6SBX98iVZfYi5SI3jpVNHsonx9vlX1cnZs6Fb7unhlQLp99YfLHzaQqZluJiKtXFnGtuj93KvTbM5JZn",
	"FMTwR+8sjDHKE6TX5ZkUU062bX+nmZU2/WYixITmnHfsmWfRjW8y16huIKf32vFMy3aV0HXztfzons+G",
	"kOvN/DWq3KErlQBb+tsSQS0hOfkDQ3u3DU6e2WV3bk1dWl09yQ8HjSf5p21P8lZV3Ly4Sy03qGFFZEsR",
	"71A5N2jMlsCkqT03UpwtKvBczDGRWYcSRMywG1jFCpV2/ZbTT2sntfx0CZ6yBApWAdMJRpBrjIALzSOE",
	"BrdQxR8UxLS5mOZJcuFCmY6r/wrrrTfewuN7a45doa0ynCWQopoh/PXf/wdSJAvIFGriacoxiTQwhXCl",
	"uDEoenDGUgIEzq2ORcjmyAwwDYUc3VG9sVgRwzew6O9qxN/nbbm9+W5UkOL56bYAOvT26o8p40mLYDfi",
	"39oWSmDQhU9WjGS9feQmLvn++1HsF2d2UV6FyW2yU9S6E8H+lqdMHClkkYWBSMuhmN1b5WqJpnLbLkpO",
	"5IyLBtRqE5Qxra+kaouoGrQKe4JiZuKmyrZ1vRRbmyG6tj0NVkLAokih1j34nREKC8plAcFRh4xPmGJz",
	"TPY0JEQwcJHlhjjHz4wsj3yPDI1U/1EM9EKZbhVMRZ9fM7VBSM5AOiKdMEStLyweWmX1jM8ERvD6wwj2",
	"fzs7fvzTQQ/eaySPGzwpgJz1i0N46oDVOB8MHoZ2O/sTg16X5uLnjCvUF7zrUAyliDQokrAg/JYLwxOb",
	"WrAbQ7G616nrdsqFG6+dnyNvrVfb+s6X5rp8DS35tQ5vMVmc0nVBp2zGBcWrDY+o10cj3GCqbxSWVGcy",
	"pdiC/k5xe2RTkMWleEOzO4ObYqeNXBUv89dy1MBm34+bcvkKK2GuFD3vWeEBN7/nCdO7Tq2ye1tnGmlY",
	"svllHmwN7Fp8+M3cotu+SXu3nKpwdsnNODdZhE2l3z1+/HiHHMGtchMU4snpxYQrE68s2ykzcQfZjfVP",
	"eUMINiu7daspV9pUcfzy8tXpzah/OVuaZrnBCJzrksqG3kF9QAA/wtijfz9CYO/bjvbgHbLoiGL0ns19",
	"s+itSBZrKZ6hiJxjLX3wG5aQ2F5g6n68NbHziVu53znQqcjdSUpZLMXyzONdbuPmSZZOBFXfaZPy5u3d",
	"LLNRmN/arMZ6I7y5AX2Fst9QubcEajfQs5W1G9Vly7nrlGfzxa+58w23+XUJiurd3DU50ULSHWXCJGki",
	"c2nHWdID8gVwiQtdAXguimpQneUeiwac/4XiuISH3EBAFhdAmCBTGlgF8YuiUSeg/4oX5etfh3vz7Hen",
	"/FsJ+RbGsOXQrsRAR0FmCSDTcKkD3OnfaWtGFVGu0LkcOy5X0zKQU6ffQJKAv/7nfyHh2tBwC7lq36E7",
	"gic1wHt0fAw6ZlkT2NacNSByDf1GMcKMz1EAmSRcMV3WqnYHx34pk1WDvvY9jWGuuFmckUtwAnJVMAI1",
	"9V8vSk1+/WHkLUuGECDXOscIJgsITt+ejaDPchP3LaYNYD/CKRc2PQMMEmZQgc4nR9pgdtAbi1EJ3vY0",
	"aD6zsO4SF8BEBKPRCYQyRZgqmULw+sPo4uz5s3fPRwH03Z+j0UkwFoVD0TFTBLV7KOYBTHlSJPysyyPe",
	"HT+19GJjMld/42IqV33aSwn7L7mAH+Hl23dvDmDCwksUESjMEhYSpXRsccv9pyy8zFh4CSxKubCVZRPj",
	"WIQJFzwk9ydJ9D0YxVxDJMPc5qi4q41rLmYJQlEclVMwKjdxvctvo9EphFIYxULzCwSSZfwolBHOUAT0",
	"QecpauAGjKSjojxEtzGqOSoSkkE1ZSECJw2js92tBPaLYEmfZbwf9MZiLH74AZ5JMUdBktBjcQSHhzXW",
	"6R0eWrQfULwfwH7VmHFgry0o4YENDYsM3FgAsOSKLUiNwySPEBgEBKwCcDo5hKAJMwK/sZEPgQUagU/7",
	"BBXYIGqJNtedQHQ9KSUZuMaBYLkADhkqcs4aGO0V7ti/gCyMmw0M5f1hRLustjPAvkZ3ASgiC7qhoVwH",
	"Jd1SGaI60FKZf3dLXVMCK3sS/OLjUfNr3bJQbOSeZdCYMmF4qO2mp+9HgY3mM0OP5+Fh5jLrh4eutFyl",
	"1q2GQfuVpge5CCsLleW2+m3darKAlFvX4lj8zLXhYkabLJnBBGM25zJXoBi9OGBiJoAkHBp49/xsVFhT",
	"k3bHkvXylhHynlUqF6YySeRVw7lax0pH7wdfSjfsO6+sh/DFue0hfEz1zIder3cO13AdHICWK8RPlS3x",
	"R3u6UXA/irjOErYAMje4RMw0XEl16aRP7oQb67KfFZb+5PSV53tzVNr5kUHvQW9Ajl5mKFjGvaH3sDfo",
	"PXSlzth63j5byvLMsKP6Uym11U3UwGaMC20gWK4FBLC/otonr/7z+YG1b9K7prYOIeARWVlnOYQ+LBc6",
	"yBIDV0ugz42GGR+CGo44d+KCw8RaH9mhhv3G2roGYte6WkJwQBo4FqFMJ1xYWvef/P7rgZM4PeqWnFeR",
	"N/ROuDatJJnfanH72B0J11P6tsXq2t8+r+jG2mFq0S+1y0ypjJ3X2WRUFrLr5pK7KtusO7JVRL1151r3",
	"3nVN9rYbny81VR0PBnfWmtOdce1o0KkmtqpNFA/a1qFHjqauoyra+41uMLvkwfYlrSYpG8HlacrUojCB",
	"JjHatbhl1ZvtF2+Ub3vhfPtQO5N06XI2I0vxWpyfUwAvXQ2lbXEuk9DMJrsAFLV5KqPFnd3IakvGdTvW",
	"JfRwvaISD74FARXe7lCIZpNs4QrvURN879Hx8fZFq51nTQ1y8iWMjVdNTdqgHdd++9nqf+HRtXu0yAGt",
	"qs2vdnxZbVpX92j10XOrSoHeRjpu182LqhbItljO5NQcOX6AiR0F45evd5v9l2g28j64b7WVl99Fpi/Q",
	"BtZlpN70oZMFFAB3rUO60cvebm6n1yPLO27Ghc/36s+KRNpO/mzwPf1ZCQLuS1XuxJsVeKhtsbCfNVuL",
	"Dra5tiqNYXNNxUO43IziUFCNRmz9ezic5UxF+3ss43sHR67izYzBNDP7H8sSvQ9lhf78IBiLaSKvhhaS",
	"NLoFXM6pSBLkHR0GsC9sh4GWhAzH4oorCutTCuMmPOFm4UKBJtRp4hzXe0BBWHdsTZ9thfvbWESrV+Oe",
	"jaHdAtFlBrmJCfKGX2kAt9bnIkPnDT+eN7W7SZeN5BSGSAiPwesPo5Za5yYu1DlrFNxvCC4bNUC/Wfrz",
	"IbC6GNh4ciwCm+69JfTccEgrL2+RZ3nsRuDZCRSrvoN/IEi8F/BTCWgj8Cn7T7876CnVej3gIQMh0NO0",
	"i4rJbRinrJN9G+/XLszeM7ZZriN23re75X8FTFMoyhotaHrIDhyz3IlmNAR1J0jwi6toyit6qW0GVc0x",
	"spqHn222O3JFjKKRfiw+5ag4aphzZqsLexp0A2rETERJlWDsQlFNxfznIKgtt7AeOK1ld3Cf9vD3AEyl",
	"710BS22vdsPXrfw/rw2Q1GbeVvKLGv+GWn67cvA25QaYLekZORYJsjkCNza/niPkIoyZmNHM591Ff9re",
	"BcH7VzEqHAsaccEDWVtZSe6MXh0MuBcf/n3w3A18+D8ax1U6vwHCNb15O3huF7Y/npOKu7qos422wE5k",
	"yBKI0Iq0zPTkKikqxsN+P6EZsdRm+PPg54G1mIKIL+sRBJfChSKoNf3mWudMhLYloEiPW/ooGuy+wQhT",
	"OVMsi3lIEb9UkW4sruO2lQ2KUoGtJrqKAhjFbGwuhXYRUobqyFaOIEXDImZYk7BWQvz8+v8DAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
