// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for PatientGender.
const (
	PatientGenderFemale PatientGender = "Female"
	PatientGenderMale   PatientGender = "Male"
	PatientGenderOther  PatientGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientGender enum.
func (e PatientGender) Valid() bool {
	switch e {
	case PatientGenderFemale:
		return true
	case PatientGenderMale:
		return true
	case PatientGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PatientCreateGender.
const (
	PatientCreateGenderFemale PatientCreateGender = "Female"
	PatientCreateGenderMale   PatientCreateGender = "Male"
	PatientCreateGenderOther  PatientCreateGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientCreateGender enum.
func (e PatientCreateGender) Valid() bool {
	switch e {
	case PatientCreateGenderFemale:
		return true
	case PatientCreateGenderMale:
		return true
	case PatientCreateGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PatientUpdateGender.
const (
	Female PatientUpdateGender = "Female"
	Male   PatientUpdateGender = "Male"
	Other  PatientUpdateGender = "Other"
)

// Valid indicates whether the value is a known member of the PatientUpdateGender enum.
func (e PatientUpdateGender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Message Human-readable error message.
	Message string `json:"message"`
}

// PaginatedPatients defines model for PaginatedPatients.
type PaginatedPatients struct {
	Data []Patient      `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	CurrentPage int   `json:"current_page"`
	LastPage    int   `json:"last_page"`
	PerPage     int   `json:"per_page"`
	Total       int64 `json:"total"`
}

// Patient defines model for Patient.
type Patient struct {
	Address     *string              `json:"address,omitempty"`
	CreatedAt   time.Time            `json:"created_at"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	DeletedAt   *time.Time           `json:"deleted_at,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`

	// FullName Computed accessor — `first_name` + " " + `last_name`. Read-only.
	FullName  *string        `json:"full_name,omitempty"`
	Gender    *PatientGender `json:"gender,omitempty"`
	Id        int64          `json:"id"`
	LastName  string         `json:"last_name"`
	Phone     *string        `json:"phone,omitempty"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// PatientGender defines model for Patient.Gender.
type PatientGender string

// PatientCreate defines model for PatientCreate.
type PatientCreate struct {
	Address     *string              `json:"address,omitempty"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`
	Gender      *PatientCreateGender `json:"gender,omitempty"`
	LastName    string               `json:"last_name"`
	Phone       *string              `json:"phone,omitempty"`
}

// PatientCreateGender defines model for PatientCreate.Gender.
type PatientCreateGender string

// PatientEnvelope defines model for PatientEnvelope.
type PatientEnvelope struct {
	Data Patient `json:"data"`
}

// PatientUpdate All fields are optional. Only keys present in the request body
// are written; explicit `null` clears a nullable column.
type PatientUpdate struct {
	Address     *string              `json:"address,omitempty"`
	DateOfBirth *openapi_types.Date  `json:"date_of_birth,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   *string              `json:"first_name,omitempty"`
	Gender      *PatientUpdateGender `json:"gender,omitempty"`
	LastName    *string              `json:"last_name,omitempty"`
	Phone       *string              `json:"phone,omitempty"`
}

// PatientUpdateGender defines model for PatientUpdate.Gender.
type PatientUpdateGender string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Errors Map of field name → list of error messages, matching Laravel's 422 shape.
	Errors  map[string][]string `json:"errors"`
	Message string              `json:"message"`
}

// Page defines model for Page.
type Page = int

// PatientId defines model for PatientId.
type PatientId = int64

// PerPage defines model for PerPage.
type PerPage = int

// Search defines model for Search.
type Search = string

// Sort defines model for Sort.
type Sort = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListPatientsParams defines parameters for ListPatients.
type ListPatientsParams struct {
	// Page 1-indexed page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Page size.
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Search Case-insensitive substring match across the resource's searchable columns.
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Column to sort by. Prefix with `-` for descending (e.g. `-created_at`).
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`
}

// CreatePatientJSONRequestBody defines body for CreatePatient for application/json ContentType.
type CreatePatientJSONRequestBody = PatientCreate

// UpdatePatientJSONRequestBody defines body for UpdatePatient for application/json ContentType.
type UpdatePatientJSONRequestBody = PatientUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List patients with pagination, search, and sort.
	// (GET /patients)
	ListPatients(c *gin.Context, params ListPatientsParams)
	// Create a new patient.
	// (POST /patients)
	CreatePatient(c *gin.Context)
	// Soft-delete a patient.
	// (DELETE /patients/{id})
	DeletePatient(c *gin.Context, id PatientId)
	// Fetch a single patient by id.
	// (GET /patients/{id})
	GetPatient(c *gin.Context, id PatientId)
	// Update a patient (partial merge).
	// (PUT /patients/{id})
	UpdatePatient(c *gin.Context, id PatientId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListPatients operation middleware
func (siw *ServerInterfaceWrapper) ListPatients(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPatientsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPatients(c, params)
}

// CreatePatient operation middleware
func (siw *ServerInterfaceWrapper) CreatePatient(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePatient(c)
}

// DeletePatient operation middleware
func (siw *ServerInterfaceWrapper) DeletePatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePatient(c, id)
}

// GetPatient operation middleware
func (siw *ServerInterfaceWrapper) GetPatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPatient(c, id)
}

// UpdatePatient operation middleware
func (siw *ServerInterfaceWrapper) UpdatePatient(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PatientId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePatient(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/patients", wrapper.ListPatients)
	router.POST(options.BaseURL+"/patients", wrapper.CreatePatient)
	router.DELETE(options.BaseURL+"/patients/:id", wrapper.DeletePatient)
	router.GET(options.BaseURL+"/patients/:id", wrapper.GetPatient)
	router.PUT(options.BaseURL+"/patients/:id", wrapper.UpdatePatient)
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse ValidationError

type ListPatientsRequestObject struct {
	Params ListPatientsParams
}

type ListPatientsResponseObject interface {
	VisitListPatientsResponse(w http.ResponseWriter) error
}

type ListPatients200JSONResponse PaginatedPatients

func (response ListPatients200JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatients400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPatients400JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPatients401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPatients401JSONResponse) VisitListPatientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatientRequestObject struct {
	Body *CreatePatientJSONRequestBody
}

type CreatePatientResponseObject interface {
	VisitCreatePatientResponse(w http.ResponseWriter) error
}

type CreatePatient201JSONResponse PatientEnvelope

func (response CreatePatient201JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePatient400JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePatient401JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePatient422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreatePatient422JSONResponse) VisitCreatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePatientRequestObject struct {
	Id PatientId `json:"id"`
}

type DeletePatientResponseObject interface {
	VisitDeletePatientResponse(w http.ResponseWriter) error
}

type DeletePatient204Response struct {
}

func (response DeletePatient204Response) VisitDeletePatientResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePatient401JSONResponse) VisitDeletePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePatient404JSONResponse struct{ NotFoundJSONResponse }

func (response DeletePatient404JSONResponse) VisitDeletePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatientRequestObject struct {
	Id PatientId `json:"id"`
}

type GetPatientResponseObject interface {
	VisitGetPatientResponse(w http.ResponseWriter) error
}

type GetPatient200JSONResponse PatientEnvelope

func (response GetPatient200JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPatient401JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPatient404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPatient404JSONResponse) VisitGetPatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatientRequestObject struct {
	Id   PatientId `json:"id"`
	Body *UpdatePatientJSONRequestBody
}

type UpdatePatientResponseObject interface {
	VisitUpdatePatientResponse(w http.ResponseWriter) error
}

type UpdatePatient200JSONResponse PatientEnvelope

func (response UpdatePatient200JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdatePatient401JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdatePatient404JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePatient422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdatePatient422JSONResponse) VisitUpdatePatientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List patients with pagination, search, and sort.
	// (GET /patients)
	ListPatients(ctx context.Context, request ListPatientsRequestObject) (ListPatientsResponseObject, error)
	// Create a new patient.
	// (POST /patients)
	CreatePatient(ctx context.Context, request CreatePatientRequestObject) (CreatePatientResponseObject, error)
	// Soft-delete a patient.
	// (DELETE /patients/{id})
	DeletePatient(ctx context.Context, request DeletePatientRequestObject) (DeletePatientResponseObject, error)
	// Fetch a single patient by id.
	// (GET /patients/{id})
	GetPatient(ctx context.Context, request GetPatientRequestObject) (GetPatientResponseObject, error)
	// Update a patient (partial merge).
	// (PUT /patients/{id})
	UpdatePatient(ctx context.Context, request UpdatePatientRequestObject) (UpdatePatientResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListPatients operation middleware
func (sh *strictHandler) ListPatients(ctx *gin.Context, params ListPatientsParams) {
	var request ListPatientsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPatients(ctx, request.(ListPatientsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPatients")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListPatientsResponseObject); ok {
		if err := validResponse.VisitListPatientsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePatient operation middleware
func (sh *strictHandler) CreatePatient(ctx *gin.Context) {
	var request CreatePatientRequestObject

	var body CreatePatientJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePatient(ctx, request.(CreatePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreatePatientResponseObject); ok {
		if err := validResponse.VisitCreatePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePatient operation middleware
func (sh *strictHandler) DeletePatient(ctx *gin.Context, id PatientId) {
	var request DeletePatientRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePatient(ctx, request.(DeletePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeletePatientResponseObject); ok {
		if err := validResponse.VisitDeletePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPatient operation middleware
func (sh *strictHandler) GetPatient(ctx *gin.Context, id PatientId) {
	var request GetPatientRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPatient(ctx, request.(GetPatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPatientResponseObject); ok {
		if err := validResponse.VisitGetPatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePatient operation middleware
func (sh *strictHandler) UpdatePatient(ctx *gin.Context, id PatientId) {
	var request UpdatePatientRequestObject

	request.Id = id

	var body UpdatePatientJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePatient(ctx, request.(UpdatePatientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePatient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdatePatientResponseObject); ok {
		if err := validResponse.VisitUpdatePatientResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFptb9s4Ev4rA+0Bm6TyS7Pdw8LFfWi7abe99Bok7vVDHYS0OLa4kUiVpJx4AwP36X7A4X7h/pLDkLIt",
	"+TW9ZrNAgdoSORzOPPPMi3MXJTovtELlbNS7iwpueI4Ojf92xsdI/wu0iZGFk1pFvehpSyqBtyig4GME",
	"VeZDNO0ojiS9/VKimUZxpHiOUS+iJVEc2STFnAdZI15mLuo9jaNcKpmXuf/spgWtl8rhGE00m8XRGXcS",
	"lXsr1nWoXsHbnxcHF9yly3OliOLI4JdSGhRRz5kS61qMtMm5C+f99Vm0XxU0m41BT8HK33CrAdBcbTfC",
	"8Y9xlPPb6uhud68iF8hNkq7r8YpbbEllUVnp5ATBlkPrjFRjyLlLUuCJ0daCSxEMWl2aBL+3YL04PswQ",
	"Ep2VubLb7hFWNm5RqReOCdpp4zbo5iWD02C1cTCctuHM4Ejewo10KbAWg5E2QJtQCVL5ANvjNrBWYpA7",
	"FFfcscOtitGZu9SaERBsoZVFj+qXXJzjlxKtVzXRyqHyH3lRZDLhpHXnV0uq39XE/sXgKOpF33WWEdMJ",
	"b23nxBhtwlHNq7/nGUENBXitYRlfoA2YoAYMtZi2o1kc/UO717pU4o9X7LzCACjtYERnegU+Kl66VBv5",
	"Gz6CEu+lteRubUCqCc+kgCFygwacvkblNfonPfanBjEPpdSq3I02WroHRlxmKGCy2Nb2iK/E0WkL/Qqj",
	"CzROBrjlaO1G6vilzLlqGeTCxx/SdqhWE9jXw2vJZ58XYi8XC/XwV0xc5IlzLBUFTkWTdl0rwZ03kXSY",
	"2322qsSQ6Oosbgyf0vccHd+/3asjtXpPq1dv4lWpJO24zXz72lWS0hhULrAsGXwHg8ZRxu19ly6oe+9K",
	"px3PdueV7kY6r9uhcY+4njiC+Lrum+0UvLRmIC6EQRvAyG9PUY1dSqnnxzhSZZYR+uYZcgVzcbRk4Mb1",
	"BHfYcjLHaMMeenmlR1dDaVy6ti26x6kCM9xz6l4ZmHPZ9El4EteN4FPuXlEjaay7Cvnmbm37+vIyyxar",
	"V1NhXpQOBfAkQWu1gd//9V9gywMYPIFBRP+eAPP+9k/bcI5ctLTKpm1f2HDxQWXTrRqPUQn0ZISK0PeZ",
	"MhGZ7TXm4cMHl6IhHO29vRQbkb0ltO5tpSLVanXl8X28URbiKyG5Emi+Nqz5tK553XsN9DfO3RF+r/yW",
	"rwrCrw+gbwD7V4I7l2rx/dtwtrZ3J1z2nLsNPLsdv8XnO7x5oiaY6QK3J9B75c1NGW/HqR890tbZ40WW",
	"wUhiJixwg6D9c561gbgArnFqoTBoqTGSqir1lyXMQNGmGyOdQ/Uc8JZKJ+mAUcQxSDLkxgKHeQBWHUF7",
	"oCgbPVhG+fbs8GjM/nDg36vIHxEMew6dbQDghmq76Xlfpc4xIAP+zhorFhXlmp6rteNqq1SAHgV8A1kC",
	"fv/3fyCT1tHjRnVs49DUUu9wyg2fYPa9hWfHx2BTXtSL5+XNamU43vK8ILNE/RRhLCeogEISbridNyL3",
	"L8DjuU3WA5r6A0xKI930gighGCi0OC/KgP7w7fUcye8+9aNVy7z71AdpbYkChlNgZx8u+tChPq2T6bFU",
	"DA4EjqRCQVHPIeMODfX/LeuwOGwPFF3Td1TU8cuxIrtd4xS4EtDvn0Kic4SR0Tmwd5/6Vxcnr85P+gw6",
	"4Wu/f8oGqiIUm3KDAlgb1YTBSGYY+MFTHt093GdpvdS5IjRXUo30Oqe90XDwRip4Am8+nL8/hCFPrlEJ",
	"MFhkPCFN6djKy52XPLkueHINXORS+bGBS3GgkkwqmRD9aTJ9G/qptCB0UuaeDcPgg5rNDKHqfPUInCld",
	"upTyS79/BtRdGp6458A0L2Qr0QLHqBi9sGWOFqQDp+koUSYYBKOZoCEjOTQjniBIQhidHbzC/BvFsw4v",
	"ZIe1B2qgvvsOXmk1QUWWsAPVgqOjZa/TPjqCjxaBUb3P4GAxdTv0bmPz9sCXhtV0Y6AAeHbDpwTjJCsF",
	"AgdGjRWDgMkesHqbweKaoBiYbzRYTHLYotkgbUm3MHoivV7MLcnCVIitTjegQEPkbIGTrOSewynkSVqf",
	"Ts39h4KkrM+q4MBicAAqUWipHNTAdTjXWxtHWjOrjftb2BomTnw+cIqrl6362+U8qhIU0jJYzLlyMrFe",
	"6NnHPvPVfOEoeR4dFdw4ybOjozA3oPqeyvaAMGhmaUrIVVlZQVb60Yan1WwKufTUEq54K62TakxCVsJg",
	"iCmfSF0aMJwyDriUKyALJw7OTy76VTTVdQ9X8izvL0LsuRiTwUhnmb6pkasnVjr6gN3NaTgOrGx7cBdo",
	"uwefczuOod1uX8IMZuwQrF5TfmT8/EZ8b2vTlJaQtsj4FCjc4BqxsHCjzXWwPtGJdJ6yX1WR/uLsbRRH",
	"EzQ28Ei3/bTdJaLXBSpeyKgX/dDutn+g2oW71DNvp6jNQ8a4YVS5ALTHJVrgYy6VdY0WLa53ZjEwX32w",
	"mOJyoJjPxgwO1kB/+vbvJ4c+8gmRdRz3gElBknYc0iibKEQXx7LalDQGtmxTWLAcJWdv47ci6kWn0rrF",
	"WChuDPw/b65ml0s6fgY+i/evq8bl91haDbTvs1IbF80uV6a5x93ug80E1+dmG6aCi0VQocnXKH5W+Szo",
	"sumIhc6d2vjZb3m6f0tjKuurijLPuZlW7pwrYsM8vVjkkLjiTA9NP3z3ZQ0fk7OjxSUvqYbUYRzeBEto",
	"ZudtTKh/0LqXWkwf0Oj1vnnWLLOocJ2tefzpQx++aPM2+jt4uYqyR3R0HD07Pt6/aX2SXQdIsCu1dXgz",
	"B8oWFMziJUN27qSYBX7McFMveoHOAlsO6tjz0HDqG6q2fIIzExQeeXjrixERaszqx6+BoqJBooWJ5L74",
	"ozSjR64VhELKlcgW/N8E5s9+SR2YDYA8W9c37Ji77//xRZC6e9PiB5ymEy5q1+J7vBDPM1Pzxm/Qbb1u",
	"9zHjQV//KSZ8jb5QnFeec+4dTqFq1jay2ldmt/nvzZRlinJDfeAHLdUIZseopVnYfcilA+47LqcHKkM+",
	"QZDOlz8lQqmSlKsxrTzZPJMh8aEvPrhJ0eBA0ZNQPFC0zRv9w02hEqrWR+Hwam51Lw7v/hkcPnfJYyH4",
	"QRi8ajsWvAEHVYsBOZoxHm5j89r0waO/Pnf4fEkQD21riI2mwU51wjMQ6E2aV2RVmqxq6HudTkYrUm1d",
	"76fuT10fMZUS2/5WQ2Cux4YXqUzAYKKN8H9sUP2Mvyy5Lmf/CwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
